import { db } from './data.js';

// ============================================================
// 1. [핵심] 사이트 리소스 기반 PPT 생성기 (이미지 경로 완벽 수정판)
// ============================================================

async function createDynamicPPT() {
    // 1. 라이브러리 로드 체크
    if (typeof window.PptxGenJS === 'undefined') {
        throw new Error("PptxGenJS 라이브러리가 로드되지 않았습니다. (HTML 헤더 확인 필요)");
    }
    
    // 2. PPT 객체 생성
    let pptx = new window.PptxGenJS();
    pptx.layout = 'LAYOUT_16x9';

    // 3. 마스터 슬라이드 (브랜드 디자인)
    pptx.defineSlideMaster({
        title: 'BRAND_MASTER',
        background: { color: 'FFFFFF' },
        objects: [
            { rect: { x: 0, y: 0, w: '100%', h: 0.15, fill: '2563EB' } }, // 상단 파란 띠
            { text: { text: 'AI Design Library - Auto Generated', options: { x: 0.5, y: 0.2, color: '94a3b8', fontSize: 10 } } },
            { rect: { x: 0, y: 5.4, w: '100%', h: 0.2, fill: 'F1F5F9' } } // 하단 회색 띠
        ]
    });

    // 4. 표지 슬라이드 생성
    let slide1 = pptx.addSlide({ masterName: 'BRAND_MASTER' });
    slide1.addText("2026 Design Resource Strategy", { x: 1, y: 2, fontSize: 36, color: '1e293b', bold: true });
    slide1.addText("Based on Uploaded Assets", { x: 1, y: 2.8, fontSize: 18, color: '64748b' });
    slide1.addText("Generated by AI Helper", { x: 8, y: 5, fontSize: 12, color: '2563EB' });

    // 5. 데이터 구조 평탄화 (Object -> Array 변환)
    let allResources = [];
    if (Array.isArray(db)) {
        allResources = db; // 이미 배열이면 그대로
    } else {
        // 카테고리별로 묶여있으면 다 꺼내서 한 줄로 합침
        allResources = Object.values(db).flat();
    }

    // 데이터가 비었는지 확인
    if (!allResources || allResources.length === 0) {
        console.error("데이터가 없습니다. data.js를 확인해주세요.");
        return;
    }

    // 6. 앞에서 4개만 뽑아서 슬라이드 만들기
    const resources = allResources.slice(0, 4); 

    resources.forEach((item, index) => {
        let slide = pptx.addSlide({ masterName: 'BRAND_MASTER' });
        
        // 제목
        slide.addText(`0${index + 1}. ${item.title || 'Untitled Resource'}`, { x: 0.5, y: 0.8, fontSize: 24, color: '1e293b', bold: true });
        
        // 설명
        slide.addText(item.desc || '설명이 없습니다.', { x: 0.5, y: 1.5, w: 4.5, fontSize: 14, color: '475569', lineSpacing: 20 });
        
        // 태그
        const tags = item.tags ? item.tags.join("  ") : "#Design #Resource";
        slide.addText(`Analyzed Keywords: ${tags}`, { x: 0.5, y: 4.5, fontSize: 10, color: '2563EB' });

        // ⭐ [중요] 이미지 경로 절대 주소 변환 ⭐
        if (item.thumb) {
            try {
                // 현재 사이트 주소(window.location.href)를 기준으로 이미지의 전체 주소를 만듭니다.
                // 예: "images/a.jpg" -> "https://my-site.com/images/a.jpg"
                const absolutePath = new URL(item.thumb, window.location.href).href;
                
                console.log(`슬라이드 ${index+1} 이미지 추가:`, absolutePath); // 확인용 로그

                slide.addImage({ 
                    path: absolutePath,
                    x: 5.5, y: 1.2, w: 4, h: 3,
                    rounding: true
                });
            } catch (err) {
                console.warn(`이미지 경로 변환 실패 (${item.title}):`, err);
            }
        }
    });

    // 7. 파일 저장 (다운로드 시작)
    await pptx.writeFile({ fileName: 'AI_Analysis_Report.pptx' });
}


// ============================================================
// 2. UI 및 스타일 (기존 디자인 유지)
// ============================================================
const style = `
<style>
    @import url('https://fonts.googleapis.com/css2?family=Pretendard:wght@400;500;700&display=swap');
    
    .ai-fab { position: fixed; bottom: 30px; right: 30px; background: #1e293b; color: white; padding: 12px 24px; border-radius: 30px; display: flex; align-items: center; gap: 10px; font-family: 'Pretendard', sans-serif; font-weight: 700; box-shadow: 0 10px 25px rgba(0,0,0,0.3); cursor: pointer; z-index: 9000; transition: transform 0.2s; animation: pulse-black 2s infinite; }
    .ai-fab:hover { transform: scale(1.05); animation: none; background: black; }
    @keyframes pulse-black { 0% { box-shadow: 0 0 0 0 rgba(30, 41, 59, 0.7); } 70% { box-shadow: 0 0 0 15px rgba(30, 41, 59, 0); } 100% { box-shadow: 0 0 0 0 rgba(30, 41, 59, 0); } }
    .ai-fab span { font-size: 1rem; } .ai-icon { font-size: 1.2rem; color: #fbbf24; }
    
    .ai-tooltip { position: fixed; bottom: 95px; right: 30px; background: white; color: #334155; padding: 12px 20px; border-radius: 16px; border-bottom-right-radius: 4px; box-shadow: 0 5px 20px rgba(0,0,0,0.15); font-size: 0.95rem; font-weight: 600; z-index: 8999; font-family: 'Pretendard', sans-serif; animation: float 3s ease-in-out infinite; pointer-events: none; transition: opacity 0.3s; }
    .ai-tooltip::after { content: ''; position: absolute; bottom: -6px; right: 20px; width: 12px; height: 12px; background: white; transform: rotate(45deg); }
    @keyframes float { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(-8px); } }
    .ai-tooltip.hidden { opacity: 0; }

    .prompt-overlay { position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0, 0, 0, 0.5); backdrop-filter: blur(5px); z-index: 9998; display: none; opacity: 0; transition: opacity 0.3s ease; }
    .prompt-modal { position: fixed; top: 20%; left: 50%; transform: translateX(-50%) translateY(20px); width: 600px; max-width: 90%; background: white; border-radius: 16px; box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25); z-index: 9999; display: none; flex-direction: column; overflow: hidden; font-family: 'Pretendard', sans-serif; transition: all 0.3s ease; }
    
    .input-area { display: flex; align-items: center; padding: 20px 24px; border-bottom: 1px solid transparent; }
    .input-area.has-result { border-bottom: 1px solid #f1f5f9; }
    .magic-icon { font-size: 1.5rem; margin-right: 15px; color: #64748b; animation: spin-slow 10s infinite linear; }
    .prompt-input { flex: 1; border: none; outline: none; font-size: 1.2rem; font-weight: 500; color: #1e293b; background: transparent; }
    .prompt-input::placeholder { color: #cbd5e1; }
    
    .result-area { background: #f8fafc; padding: 0; max-height: 0; overflow-y: auto; transition: max-height 0.4s ease, padding 0.4s ease; }
    .result-content { font-size: 1rem; line-height: 1.7; color: #334155; white-space: pre-wrap; }
    .result-area.show { padding: 24px; max-height: 300px; }
    
    .chips-area { padding: 12px 24px 20px 24px; display: flex; gap: 8px; flex-wrap: wrap; }
    .chip { background: white; border: 1px solid #e2e8f0; border-radius: 20px; padding: 6px 14px; font-size: 0.85rem; color: #64748b; cursor: pointer; transition: 0.2s; display: flex; align-items: center; gap: 6px; }
    .chip:hover { border-color: #2563eb; color: #2563eb; background: #eff6ff; }
    
    @keyframes spin-slow { 100% { transform: rotate(360deg); } }
    .blinking-cursor { display: inline-block; width: 6px; height: 18px; background: #2563eb; animation: blink 1s infinite; vertical-align: middle; margin-left: 4px; }
    @keyframes blink { 50% { opacity: 0; } }
</style>
`;
document.head.insertAdjacentHTML('beforeend', style);

// HTML 구조 렌더링
const html = `
    <div class="ai-tooltip" id="aiTooltip">🤖 필요한 자료를 AI에게 물어보세요!</div>
    <div class="ai-fab" onclick="openPrompt()">
        <i class="ph-fill ph-sparkle ai-icon"></i><span>Ask AI</span>
    </div>
    <div class="prompt-overlay" id="promptOverlay" onclick="closePrompt()"></div>
    <div class="prompt-modal" id="promptModal">
        <div class="input-area" id="inputArea">
            <i class="ph-fill ph-sparkle magic-icon"></i>
            <input type="text" class="prompt-input" id="promptInput" placeholder="무엇을 찾아드릴까요? (예: PPT 만들어줘)" autocomplete="off" onkeypress="handleEnter(event)">
        </div>
        <div class="chips-area" id="chipsArea">
            <div class="chip" onclick="askChip('전략 보고서 PPT 만들어줘')"><i class="ph-fill ph-slideshow"></i> PPT 5장 생성</div>
            <div class="chip" onclick="askChip('전략 보고서 찾아줘')"><i class="ph ph-magnifying-glass"></i> 전략 보고서</div>
            <div class="chip" onclick="askChip('다운로드 오류 해결법')"><i class="ph ph-warning-circle"></i> 다운로드 오류</div>
        </div>
        <div class="result-area" id="resultArea">
            <div class="result-content" id="resultContent"></div>
        </div>
    </div>
`;
document.body.insertAdjacentHTML('beforeend', html);


// ============================================================
// 3. 로직 (Logic)
// ============================================================

const overlay = document.getElementById('promptOverlay');
const modal = document.getElementById('promptModal');
const input = document.getElementById('promptInput');
const resultArea = document.getElementById('resultArea');
const resultContent = document.getElementById('resultContent');
const chipsArea = document.getElementById('chipsArea');
const tooltip = document.getElementById('aiTooltip');

window.openPrompt = function() {
    overlay.style.display = 'block';
    modal.style.display = 'flex';
    tooltip.classList.add('hidden');
    setTimeout(() => { overlay.style.opacity = '1'; modal.style.transform = 'translateX(-50%) translateY(0)'; modal.style.opacity = '1'; input.focus(); }, 10);
}

window.closePrompt = function() {
    overlay.style.opacity = '0';
    modal.style.opacity = '0';
    modal.style.transform = 'translateX(-50%) translateY(20px)';
    setTimeout(() => { overlay.style.display = 'none'; modal.style.display = 'none'; tooltip.classList.remove('hidden'); resetPrompt(); }, 300);
}

window.handleEnter = function(e) { if (e.key === 'Enter') runAI(); }
window.askChip = function(question) { input.value = question; runAI(); }

function runAI() {
    const text = input.value.trim();
    if (!text) return;

    chipsArea.style.display = 'none';
    document.getElementById('inputArea').classList.add('has-result');
    resultArea.classList.add('show');
    resultContent.innerHTML = '<span style="color:#64748b">AI가 데이터를 분석하여 PPT 구조를 설계 중입니다... <span class="blinking-cursor"></span></span>';

    setTimeout(async () => {
        // 🔥 PPT 생성 명령어 인식
        if (text.includes("PPT") || text.includes("만들어") || text.includes("슬라이드")) {
            
            resultContent.innerHTML = "✅ <strong>디자인 리소스를 기반으로 PPT 생성을 시작합니다!</strong><br><br><code>data.js</code>의 데이터를 분석하여 슬라이드에 이미지를 배치합니다...";
            
            try {
                // ⭐ 여기서 진짜 PPT 생성 함수 실행
                await createDynamicPPT(); 
                
                setTimeout(() => {
                    typeWriter("🎉 <strong>PPT 생성이 완료되었습니다!</strong><br>다운로드된 파일을 열어보세요.<br>사이트에 있는 <strong>썸네일 이미지</strong>가 실제로 슬라이드에 포함되었습니다.");
                }, 1500);
            } catch (e) {
                console.error(e);
                typeWriter(`❌ PPT 생성 오류: ${e.message}<br>브라우저 콘솔(F12)을 확인해주세요.`);
            }

        } else {
            // 일반 대화 (가짜 답변)
            let answer = "죄송해요, 그건 제가 할 수 없는 일이에요. 😅";
            if (text.includes("보고서")) answer = "네, <strong>101번 '2026 전략 보고서'</strong>가 가장 적합해 보입니다.";
            else if (text.includes("안녕")) answer = "반갑습니다! AI 디자인 헬퍼입니다. 🤖";
            else if (text.includes("다운") || text.includes("오류")) answer = "다운로드 버튼을 누르시면 구글 드라이브 뷰어가 새 창으로 열립니다.";
            
            typeWriter(answer);
        }
    }, 1500);
}

function typeWriter(htmlText) {
    resultContent.style.opacity = 0;
    resultContent.innerHTML = htmlText;
    let op = 0.1;
    let timer = setInterval(function () {
        if (op >= 1) clearInterval(timer);
        resultContent.style.opacity = op;
        op += op * 0.1;
    }, 30);
}

function resetPrompt() {
    input.value = '';
    resultArea.classList.remove('show');
    document.getElementById('inputArea').classList.remove('has-result');
    chipsArea.style.display = 'flex';
    resultContent.innerHTML = '';
}

// 키보드 이벤트
document.addEventListener('keydown', (e) => {
    if ((e.metaKey || e.ctrlKey) && e.key === 'k') { e.preventDefault(); if (modal.style.display === 'flex') closePrompt(); else openPrompt(); }
    if (e.key === 'Escape') closePrompt();
});